### ISSUE TITLE
DESCRIPTION's bug report url invalid

### ISSUE THREAD

**Issue by jangorecki** [metrumresearchgroup/vcs#1]
it points to https://github.com/metrumresearchgroup/options/issues

**Comment by yonicd** [comment]
You are welcome to PR a correction. I will not have time to get to this in the next few days. 

Thanks!

**Comment by yonicd** [comment]
fixed. https://github.com/metrumresearchgroup/vcs/commit/fa0a10b84df27c18addcd63b958155aab3d33398
